### ISSUE TITLE
[Bug] If the content height of the content area of the metedata page exceeds the height of the window, it will cause page layout problems

### ISSUE THREAD

**Issue by s7monk** [apache/paimon-webui#177]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon-webui/issues) and found nothing similar.

### Paimon UI version

main

### Compute Engine

Flink

### Minimal reproduce step

![image](https://github.com/apache/incubator-paimon-webui/assets/34889415/0bff004b-89d4-4693-8582-ae5acc9ac127)

![image](https://github.com/apache/incubator-paimon-webui/assets/34889415/f96070b2-2486-4c3e-8833-0717d24b0c8b)

### What doesn't meet your expectations?

If the content height of the content area of the metedata page exceeds the height of the window, it will cause page layout problems.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by zhangmo8** [comment]
What's this?
