### ISSUE TITLE
[Feature] Paimon CDC integration

### ISSUE THREAD

**Issue by s7monk** [apache/paimon-webui#24]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon-webui/issues) and found nothing similar.

### Motivation

Paimon currently provides the actions of MySQL and Kafka CDC entering the lake, but it needs to maintain a lot of action scripts for CDC entering the lake, which is not very user-friendly, so we can use the UI to manage the actions of Paimon CDC, which requires development and management The function of Flink Action supports one-click implementation of CDC data such as MySQL, Kafka, and PostgreSQL into the lake through the UI.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by silenceland** [comment]
hello, i am interesting about this issue, and i can try to solve this, please assign it to me, thanks very much!

**Comment by SteNicholas** [comment]
@silenceland, thanks for taking this ticket. Assigned.
