### ISSUE TITLE
[Bug] [ui] Autofill style error in login page

### ISSUE THREAD

**Issue by hdygxsj** [apache/paimon-webui#295]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/paimon-webui/issues) and found nothing similar.

### Paimon UI version

main

### Compute Engine

Flink

### Minimal reproduce step

The background color is changed when the form auto-fills.
<img width="1694" alt="image" src="https://github.com/apache/paimon-webui/assets/35210666/4d9e1c4b-b076-46d1-b9a9-ae235958dd94">

### What doesn't meet your expectations?

none

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by zhangmo8** [comment]
This is a browser problem, and if you need to fix it, may need to disable automatic padding.
