### ISSUE TITLE
[Bug] [ui] User management, when updating a user, the mobile phone number recognition error

### ISSUE THREAD

**Issue by AnemoneIndicum** [apache/paimon-webui#363]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/paimon-webui/issues) and found nothing similar.

### Paimon UI version

main

### Compute Engine

Flink

### Minimal reproduce step

Front-end mobile phone number identification problem, I tested 15926633887 13972235452, but I found that the former had a verification error, while the latter could be recognized.

### What doesn't meet your expectations?

The front-end mobile phone number verification should include all recognizable mobile phone numbers.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by hdygxsj** [comment]
It was repaired in  #403 @SteNicholas

**Comment by AnemoneIndicum** [comment]
I will close this issue.
