### ISSUE TITLE
[Bug]  CdcJobDefinition list page return CreateUser

### ISSUE THREAD

**Issue by XianmingZhou00** [apache/paimon-webui#365]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/paimon-webui/issues) and found nothing similar.

### Paimon UI version

main

### Compute Engine

Flink

### Minimal reproduce step

  
<img width="947" alt="1718256594330" src="https://github.com/apache/paimon-webui/assets/147145809/e77cea50-ec54-4425-9187-109158132e25">

### What doesn't meet your expectations?

 CdcJobDefinition list page return CreateUser is null.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by AnemoneIndicum** [comment]
I can handle this.
