### ISSUE TITLE
[Bug] create hive-catalog error

### ISSUE THREAD

**Issue by yaofengchn** [apache/paimon-webui#371]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/paimon-webui/issues) and found nothing similar.

### Paimon UI version

main

### Compute Engine

Flink

### Minimal reproduce step

<img width="951" alt="image" src="https://github.com/apache/paimon-webui/assets/31480221/c8019082-d420-4930-85b9-626b7cde7bd6">

![image](https://github.com/apache/paimon-webui/assets/31480221/8839e358-9e03-41ae-bf5d-8fd64cc77522)

创建hive catelog的时候，发现hive uri和hive conf没传到后端，导致报错

### What doesn't meet your expectations?

不应该报错

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by s7monk** [comment]
This problem is because the front-end does not pass the HiveUrl to the back-end. I will fix it.
![image](https://github.com/apache/paimon-webui/assets/34889415/be98f667-e6ac-4809-82c9-406c027eef80)
