### ISSUE TITLE
[Feature] Metadata prototype diagram

### ISSUE THREAD

**Issue by s7monk** [apache/paimon-webui#50]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon-webui/issues) and found nothing similar.

### Motivation

![image](https://github.com/apache/incubator-paimon-webui/assets/34889415/419b4304-d1d4-4711-8474-8d6e7b3ab9a3)

![image](https://github.com/apache/incubator-paimon-webui/assets/34889415/a14e28c5-14bc-48fd-a0de-b7035ffecfac)

![image](https://github.com/apache/incubator-paimon-webui/assets/34889415/84bf86ec-f96c-464d-8dde-8fe924928081)

![image](https://github.com/apache/incubator-paimon-webui/assets/34889415/794de601-0b34-4bc5-bc98-3ccbb5f11335)

![image](https://github.com/apache/incubator-paimon-webui/assets/34889415/3c566210-a546-40f6-b761-e7444563c245)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by labbomb** [comment]
LGTM.

**Comment by hdygxsj** [comment]
If needed, I can complete the development of the back-end part of this feature

**Comment by hunter-cloud09** [comment]
@hdygxsj Thank you for your attention. This content has been developed #54 . We will launch other issues in the future. You are welcome to provide PR.

**Comment by s7monk** [comment]
> > @hdygxsj Thank you for your attention. This content has been developed #54 . We will launch other issues in the future. You are welcome to provide PR.
> 
> Is paimon-web-ui ready to be deprecated? I found that the MetaData module failed to call the back-end endpoint because the address and parameters of the font end request were inconsistent with those of the back-end endpoint. Need to fix them？

The front end currently uses paimon-web-ui-new

**Comment by zhangmo8** [comment]
<img width="1335" alt="image" src="https://github.com/apache/incubator-paimon-webui/assets/43628500/0a815e4a-23de-4554-a2c8-e00747e2e3a3">

<img width="709" alt="image" src="https://github.com/apache/incubator-paimon-webui/assets/43628500/91f3bd9b-a2ae-4f1c-a4e3-a9f2d97ec67d">

<img width="845" alt="image" src="https://github.com/apache/incubator-paimon-webui/assets/43628500/c16e2675-aafd-4114-ad11-fc85af476d8a">
