### ISSUE TITLE
[Feature] Job Management prototype diagram

### ISSUE THREAD

**Issue by s7monk** [apache/paimon-webui#91]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon-webui/issues) and found nothing similar.

### Motivation

![ec528c28ebe6c38933fdbf6b4527b2c](https://github.com/apache/incubator-paimon-webui/assets/34889415/091c42fa-cdcf-41c6-8358-78f86d88dbc8)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by zhangmo8** [comment]
#96
