### ISSUE TITLE
[Feature] Support for creating catalogs using S3 and OSS

### ISSUE THREAD

**Issue by hdygxsj** [apache/paimon-webui#98]
### Search before asking

- [X] I searched in the [issues](https://github.com/apache/incubator-paimon-webui/issues) and found nothing similar.

### Motivation

Now that warehourse supports local files when using the file system to create the Catalog, do we need to make it support other object storage?
<img width="687" alt="image" src="https://github.com/apache/incubator-paimon-webui/assets/35210666/390625b8-c11e-498c-889f-12ed62bc3384">

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by hunter-cloud09** [comment]
Do you have WeChat? I mean I can pull you into the development group.

**Comment by hdygxsj** [comment]
My WeChat is 15016895609


在 2023年11月22日 ***@***.***> 写道：


Do you have WeChat? I mean I can pull you into the development group.
